### PR TITLE
Update README.md and ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by TranceAccount**
Greetings,

I have made a few changes to the contents of README.md and ISSUE_TEMPLATE.md.
It is up to you to either merge or close this.

### CODE REVIEW

**Comment by TranceAccount** [comment]
Bump?

**Comment by Malylolek** [comment]
Make BugTracker great again bump !

**Comment by TranceAccount** [comment]
Bump

**Comment by TranceAccount** [comment]
> Bump

**Comment by TranceAccount** [comment]
>> Bump

**Pull request merged**
